export const userConstants = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  USER_LOGIN_RESET: "USER_LOGIN_RESET",

  USER_SIGNUP_REQUEST: "USER_SIGNUP_REQUEST",
  USER_SIGNUP_SUCCESS: "USER_SIGNUP_SUCCESS",
  USER_SIGNUP_FAILURE: "USER_SIGNUP_FAILURE",
  USER_SIGNUP_RESET: "USER_SIGNUP_RESET",

  USER_SIGNOUT_REQUEST: "USER_SIGNOUT_REQUEST",
  USER_SIGNOUT_SUCCESS: "USER_SIGNOUT_SUCCESS",
  USER_SIGNOUT_FAILURE: "USER_SIGNOUT_FAILURE",
  USER_SIGNOUT_RESET: "USER_SIGNOUT_RESET",
};

export const categoryConstants = {
  CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",

  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",

  GET_SINGLE_CATEGORY_REQUEST: "GET_SINGLE_CATEGORY_REQUEST",
  GET_SINGLE_CATEGORY_SUCCESS: "GET_SINGLE_CATEGORY_SUCCESS",
  GET_SINGLE_CATEGORY_FAILURE: "GET_SINGLE_CATEGORY_FAILURE",
};

export const tagConstants = {
  GET_ALL_TAG_REQUEST: "GET_ALL_TAG_REQUEST",
  GET_ALL_TAG_SUCCESS: "GET_ALL_TAG_SUCCESS",
  GET_ALL_TAG_FAILURE: "GET_ALL_TAG_FAILURE",

  CREATE_TAG_REQUEST: "CREATE_TAG_REQUEST",
  CREATE_TAG_SUCCESS: "CREATE_TAG_SUCCESS",
  CREATE_TAG_FAILURE: "CREATE_TAG_FAILURE",

  DELETE_TAG_REQUEST: "DELETE_TAG_REQUEST",
  DELETE_TAG_SUCCESS: "DELETE_TAG_SUCCESS",
  DELETE_TAG_FAILURE: "DELETE_TAG_FAILURE",
};

export const blogContstants = {
  GET_ALL_BLOG_REQUEST: "GET_ALL_BLOG_REQUEST",
  GET_ALL_BLOG_SUCCESS: "GET_ALL_BLOG_SUCCESS",
  GET_ALL_BLOG_FAILURE: "GET_ALL_BLOG_FAILURE",

  GET_SINGLE_BLOG_REQUEST: "GET_SINGLE_BLOG_REQUEST",
  GET_SINGLE_BLOG_SUCCESS: "GET_SINGLE_BLOG_SUCCESS",
  GET_SINGLE_BLOG_FAILURE: "GET_SINGLE_BLOG_FAILURE",

  DELETE_BLOG_REQUEST: "DELETE_BLOG_REQUEST",
  DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAILURE: "DELETE_BLOG_FAILURE",

  CREATE_BLOG_REQUEST: "CREATE_BLOG_REQUEST",
  CREATE_BLOG_SUCCESS: "CREATE_BLOG_SUCCESS",
  CREATE_BLOG_FAILURE: "CREATE_BLOG_FAILURE",

  UPDATE_BLOG_REQUEST: "UPDATE_BLOG_REQUEST",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
  UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",

  GET_BLOG_BY_CATEGORY_REQUEST: "GET_BLOG_BY_CATEGORY_REQUEST",
  GET_BLOG_BY_CATEGORY_SUCCESS: "GET_BLOG_BY_CATEGORY_SUCCESS",
  GET_BLOG_BY_CATEGORY_FAILURE: "GET_BLOG_BY_CATEGORY_FAILURE",

  GET_PHOTO_BLOG_SUCCESS: "GET_PHOTO_BLOG_SUCCESS",
  GET_RELATED_BLOG_SUCCESS: "GET_RELATED_BLOG_SUCCESS",
  GET_LATEST_BLOG_SUCCESS: "GET_LATEST_BLOG_SUCCESS",

  RESET_BLOG_SUCCESS: "RESET_BLOG_SUCCESS",
};
