export const authConstants = {
  AUTH_LOGIN_REQUEST: "AUTH_LOGIN_REQUEST",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_FAILURE: "AUTH_LOGIN_FAILURE",
  AUTH_LOGIN_RESET: "AUTH_LOGIN_RESET",

  AUTH_SIGNUP_REQUEST: "AUTH_SIGNUP_REQUEST",
  AUTH_SIGNUP_SUCCESS: "AUTH_SIGNUP_SUCCESS",
  AUTH_SIGNUP_FAILURE: "AUTH_SIGNUP_FAILURE",
  AUTH_SIGNUP_RESET: "AUTH_SIGNUP_RESET",

  AUTH_SIGNOUT_REQUEST: "AUTH_SIGNOUT_REQUEST",
  AUTH_SIGNOUT_SUCCESS: "AUTH_SIGNOUT_SUCCESS",
  AUTH_SIGNOUT_FAILURE: "AUTH_SIGNOUT_FAILURE",
  AUTH_SIGNOUT_RESET: "AUTH_SIGNOUT_RESET",
};

export const categoryConstants = {
  CREATE_CATEGORY_REQUEST: "CREATE_CATEGORY_REQUEST",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",

  GET_ALL_CATEGORY_REQUEST: "GET_ALL_CATEGORY_REQUEST",
  GET_ALL_CATEGORY_SUCCESS: "GET_ALL_CATEGORY_SUCCESS",
  GET_ALL_CATEGORY_FAILURE: "GET_ALL_CATEGORY_FAILURE",

  DELETE_CATEGORY_REQUEST: "DELETE_CATEGORY_REQUEST",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",

  GET_SINGLE_CATEGORY_REQUEST: "GET_SINGLE_CATEGORY_REQUEST",
  GET_SINGLE_CATEGORY_SUCCESS: "GET_SINGLE_CATEGORY_SUCCESS",
  GET_SINGLE_CATEGORY_FAILURE: "GET_SINGLE_CATEGORY_FAILURE",
};

export const tagConstants = {
  GET_ALL_TAG_REQUEST: "GET_ALL_TAG_REQUEST",
  GET_ALL_TAG_SUCCESS: "GET_ALL_TAG_SUCCESS",
  GET_ALL_TAG_FAILURE: "GET_ALL_TAG_FAILURE",

  CREATE_TAG_REQUEST: "CREATE_TAG_REQUEST",
  CREATE_TAG_SUCCESS: "CREATE_TAG_SUCCESS",
  CREATE_TAG_FAILURE: "CREATE_TAG_FAILURE",

  DELETE_TAG_REQUEST: "DELETE_TAG_REQUEST",
  DELETE_TAG_SUCCESS: "DELETE_TAG_SUCCESS",
  DELETE_TAG_FAILURE: "DELETE_TAG_FAILURE",
};

export const blogContstants = {
  GET_ALL_BLOG_REQUEST: "GET_ALL_BLOG_REQUEST",
  GET_ALL_BLOG_SUCCESS: "GET_ALL_BLOG_SUCCESS",
  GET_ALL_BLOG_FAILURE: "GET_ALL_BLOG_FAILURE",

  GET_SINGLE_BLOG_REQUEST: "GET_SINGLE_BLOG_REQUEST",
  GET_SINGLE_BLOG_SUCCESS: "GET_SINGLE_BLOG_SUCCESS",
  GET_SINGLE_BLOG_FAILURE: "GET_SINGLE_BLOG_FAILURE",

  DELETE_BLOG_REQUEST: "DELETE_BLOG_REQUEST",
  DELETE_BLOG_SUCCESS: "DELETE_BLOG_SUCCESS",
  DELETE_BLOG_FAILURE: "DELETE_BLOG_FAILURE",

  CREATE_BLOG_REQUEST: "CREATE_BLOG_REQUEST",
  CREATE_BLOG_SUCCESS: "CREATE_BLOG_SUCCESS",
  CREATE_BLOG_FAILURE: "CREATE_BLOG_FAILURE",

  UPDATE_BLOG_REQUEST: "UPDATE_BLOG_REQUEST",
  UPDATE_BLOG_SUCCESS: "UPDATE_BLOG_SUCCESS",
  UPDATE_BLOG_FAILURE: "UPDATE_BLOG_FAILURE",

  GET_BLOG_BY_CATEGORY_REQUEST: "GET_BLOG_BY_CATEGORY_REQUEST",
  GET_BLOG_BY_CATEGORY_SUCCESS: "GET_BLOG_BY_CATEGORY_SUCCESS",
  GET_BLOG_BY_CATEGORY_FAILURE: "GET_BLOG_BY_CATEGORY_FAILURE",

  GET_PHOTO_BLOG_SUCCESS: "GET_PHOTO_BLOG_SUCCESS",
  GET_RELATED_BLOG_SUCCESS: "GET_RELATED_BLOG_SUCCESS",
  GET_LATEST_BLOG_SUCCESS: "GET_LATEST_BLOG_SUCCESS",

  RESET_BLOG_SUCCESS: "RESET_BLOG_SUCCESS",
};

export const userConstant = {
  GET_PUBLIC_USER_REQUEST: "GET_PUBLIC_USER_REQUEST",
  GET_PUBLIC_USER_SUCCESS: "GET_PUBLIC_USER_SUCCESS",
  GET_PUBLIC_USER_FAILURE: "GET_PUBLIC_USER_FAILURE",
};

export const profileConstant = {
  GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
  GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
  GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

  UPDATE_USER_PROFILE_REQUEST: "UPDATE_USER_PROFILE_REQUEST",
  UPDATE_USER_PROFILE_SUCCESS: "UPDATE_USER_PROFILE_SUCCESS",
  UPDATE_USER_PROFILE_FAILURE: "UPDATE_USER_PROFILE_FAILURE",
};
